In [1]:
import numpy as np

x = np.array([[14, 13, 1.50, 45],
              [16, 13, 1.60, 50],
              [15, 13, 1.65, 50],
              [9, 15, 1.75, 60],
              [10, 14, 1.70, 60],
              [7, 14, 1.70, 60],
              [8, 14, 1.60, 70],
              [13, 13, 1.60, 65],
              [17, 15, 1.55, 60],
              [11, 14, 1.70, 65]])

xt = x.T
print("Matrice x :")
print(x)
print("Matrice xt :")
print(xt)


Matrice x :
[[14.   13.    1.5  45.  ]
 [16.   13.    1.6  50.  ]
 [15.   13.    1.65 50.  ]
 [ 9.   15.    1.75 60.  ]
 [10.   14.    1.7  60.  ]
 [ 7.   14.    1.7  60.  ]
 [ 8.   14.    1.6  70.  ]
 [13.   13.    1.6  65.  ]
 [17.   15.    1.55 60.  ]
 [11.   14.    1.7  65.  ]]
Matrice xt :
[[14.   16.   15.    9.   10.    7.    8.   13.   17.   11.  ]
 [13.   13.   13.   15.   14.   14.   14.   13.   15.   14.  ]
 [ 1.5   1.6   1.65  1.75  1.7   1.7   1.6   1.6   1.55  1.7 ]
 [45.   50.   50.   60.   60.   60.   70.   65.   60.   65.  ]]


In [2]:
indiv_4_5_6 = x[3:6, :]
print("Individus 4, 5 et 6 :")
print(indiv_4_5_6)


Individus 4, 5 et 6 :
[[ 9.   15.    1.75 60.  ]
 [10.   14.    1.7  60.  ]
 [ 7.   14.    1.7  60.  ]]


In [7]:
# Création du tableau x(j)
xj = np.vstack((np.mean(x, axis=0), np.var(x, axis=0), np.std(x, axis=0)))

# Arrondir les valeurs à trois décimales
xj = np.round(xj, decimals=3)

# Affichage du tableau x(j)
print("Tableau x(j) :\n")
print(xj)

Tableau x(j) :

[[1.200e+01 1.380e+01 1.635e+00 5.850e+01]
 [1.100e+01 5.600e-01 6.000e-03 5.525e+01]
 [3.317e+00 7.480e-01 7.400e-02 7.433e+00]]


In [4]:
centre_gravite = np.mean(x, axis=0)
print("Le centre de gravité est :", centre_gravite)

Le centre de gravité est : [12.    13.8    1.635 58.5  ]


In [8]:
# Calcul de la matrice de covariance
v = np.cov(x, rowvar=False)

# Affichage de la matrice de covariance
print("Matrice de covariance :\n", v)

Matrice de covariance :
 [[ 1.22222222e+01 -8.88888889e-01 -1.72222222e-01 -1.55555556e+01]
 [-8.88888889e-01  6.22222222e-01  2.44444444e-02  3.00000000e+00]
 [-1.72222222e-01  2.44444444e-02  6.13888889e-03  2.25000000e-01]
 [-1.55555556e+01  3.00000000e+00  2.25000000e-01  6.13888889e+01]]


In [9]:
# Calcul de la matrice de corrélation
c = np.corrcoef(x, rowvar=False)

# Affichage de la matrice de corrélation
print("Matrice de corrélation :\n", c)

Matrice de corrélation :
 [[ 1.         -0.32232919 -0.62873728 -0.56789174]
 [-0.32232919  1.          0.39551461  0.48540429]
 [-0.62873728  0.39551461  1.          0.36651584]
 [-0.56789174  0.48540429  0.36651584  1.        ]]


In [10]:
moyennes = np.mean(x, axis=0)
xc = x - moyennes

v = np.cov(xc, rowvar=False)

# Calcul des valeurs propres et des vecteurs propres
valeurs_propres, vecteurs_propres = np.linalg.eig(v)

# Affichage des résultats
print("Valeurs propres :\n", valeurs_propres)
print("\nVecteurs propres :\n", vecteurs_propres)

Valeurs propres :
 [6.60477567e+01 7.71547085e+00 4.72823093e-01 3.42161997e-03]

Vecteurs propres :
 [[ 2.78058419e-01 -9.60333435e-01  1.61306890e-02  1.35280949e-02]
 [-4.77697706e-02  2.59201615e-03  9.98547501e-01 -2.47834255e-02]
 [-4.01130649e-03  1.33327223e-02  2.45830617e-02  9.99600831e-01]
 [-9.59367226e-01 -2.78523272e-01 -4.51482187e-02  9.75428278e-04]]


In [11]:
# Sélection du premier vecteur propre
premier_vp = vecteurs_propres[:, 0]

# Calcul de la matrice A (la matrice de covariance v dans notre cas)
A = v

# Calcul de la valeur propre associée au premier vecteur propre
lambda_ = valeurs_propres[0]

# Vecteur à vérifier (ici on prend le premier enfant)
y = np.array([14, 1.50, 45])

# Vérification
res = np.dot(A, y)
if np.isclose(res, lambda_ * y, rtol=1e-5).all():
    print("Le vecteur y est bien le vecteur propre associé à la valeur propre lambda.")
else:
    print("Le vecteur y n'est pas le vecteur propre associé à la valeur propre lambda.")


ValueError: shapes (4,4) and (3,) not aligned: 4 (dim 1) != 3 (dim 0)