Importation des bibliothèques

In [2]:
import statistics as st
import math 
import numpy as np
import scipy as sp 
import pandas as pd 
import matplotlib.pyplot as plt

Question 1 :
Creation du matrice des données

In [3]:
#créer la matrice de données
data = np.array (( [14,13,1.5,45], [16,13,1.6,50],[15,13,1.65,50],
            [9,15,1.75,60],[10,14,1.7,60],[7,14,1.7,60],
            [8,14,1.6,70],[13,13,1.6,65],[17,15,1.55,60],[11,14,1.7,65]))


#les dimensions de la matrice des donnés 
dataHeight = data.shape[0]
dataWidth = data.shape[1]

#la matrice transposéé data_t
data_t =np.transpose(data)

#l'affichage des deux matrice 
x = pd.DataFrame(data)
x_t = pd.DataFrame(data_t)

print("la matrice des donnés :")
print(x ,"\n")

print("la matrice des donnés transposée :")
print(x_t)

la matrice des donnés :
      0     1     2     3
0  14.0  13.0  1.50  45.0
1  16.0  13.0  1.60  50.0
2  15.0  13.0  1.65  50.0
3   9.0  15.0  1.75  60.0
4  10.0  14.0  1.70  60.0
5   7.0  14.0  1.70  60.0
6   8.0  14.0  1.60  70.0
7  13.0  13.0  1.60  65.0
8  17.0  15.0  1.55  60.0
9  11.0  14.0  1.70  65.0 

la matrice des donnés transposée :
      0     1      2      3     4     5     6     7      8     9
0  14.0  16.0  15.00   9.00  10.0   7.0   8.0  13.0  17.00  11.0
1  13.0  13.0  13.00  15.00  14.0  14.0  14.0  13.0  15.00  14.0
2   1.5   1.6   1.65   1.75   1.7   1.7   1.6   1.6   1.55   1.7
3  45.0  50.0  50.00  60.00  60.0  60.0  70.0  65.0  60.00  65.0


Question 2 : la liste des individus 

In [4]:
for i in range(dataHeight):
    print("Individus "+str(i+1)+":")
    print(data[i,:].tolist(),"\n")

Individus 1:
[14.0, 13.0, 1.5, 45.0] 

Individus 2:
[16.0, 13.0, 1.6, 50.0] 

Individus 3:
[15.0, 13.0, 1.65, 50.0] 

Individus 4:
[9.0, 15.0, 1.75, 60.0] 

Individus 5:
[10.0, 14.0, 1.7, 60.0] 

Individus 6:
[7.0, 14.0, 1.7, 60.0] 

Individus 7:
[8.0, 14.0, 1.6, 70.0] 

Individus 8:
[13.0, 13.0, 1.6, 65.0] 

Individus 9:
[17.0, 15.0, 1.55, 60.0] 

Individus 10:
[11.0, 14.0, 1.7, 65.0] 



Question 3 : la liste des variables 

In [5]:
for i in range(dataWidth):
    print("Variable "+str(i+1)+":")
    print(data[:,i].tolist(),"\n")

Variable 1:
[14.0, 16.0, 15.0, 9.0, 10.0, 7.0, 8.0, 13.0, 17.0, 11.0] 

Variable 2:
[13.0, 13.0, 13.0, 15.0, 14.0, 14.0, 14.0, 13.0, 15.0, 14.0] 

Variable 3:
[1.5, 1.6, 1.65, 1.75, 1.7, 1.7, 1.6, 1.6, 1.55, 1.7] 

Variable 4:
[45.0, 50.0, 50.0, 60.0, 60.0, 60.0, 70.0, 65.0, 60.0, 65.0] 



Question 4 : Acceder aux individus 4,5,6

In [6]:
for i in range(3,6):
    print("Individus "+str(i+1)+":")
    print(data[i,:].tolist(),"\n")

Individus 4:
[9.0, 15.0, 1.75, 60.0] 

Individus 5:
[10.0, 14.0, 1.7, 60.0] 

Individus 6:
[7.0, 14.0, 1.7, 60.0] 



Question 5 : 

In [7]:
#Calculer la moyenne arithmétique de chaque variable
meanArr = []
for i in range(0,4) :
    meanArr.append(np.mean(data[:,i]))
#print(meanArr)

#Calculer la variance de chaque varible 
varArr = []
for i in range(0,4) :
    varArr.append(np.var(data[:,i]))
#print(varArr)



#Calaculer l'ecart type de chaque varible
stdArr = []
for i in range(0,4) :
    stdArr.append(math.sqrt(varArr[i]))
#print(stdArr)

#Construction du tableau X
X = np.array([[meanArr],[varArr],[stdArr]])
X = np.round(X,3)
print("la matrice X :"'\n',X)



la matrice X :
 [[[1.200e+01 1.380e+01 1.635e+00 5.850e+01]]

 [[1.100e+01 5.600e-01 6.000e-03 5.525e+01]]

 [[3.317e+00 7.480e-01 7.400e-02 7.433e+00]]]


Question 6 : le centre de gravité du nuage des donnés

In [8]:
centreDeGravite = meanArr
print("le centre de gravité :"'\n',pd.DataFrame(data=centreDeGravite))

le centre de gravité :
         0
0  12.000
1  13.800
2   1.635
3  58.500


Question 7 : les covariances possibles

In [9]:
#Matrice des covariances 
covMatrix = np.round(np.cov(data, bias=False , rowvar=False), 3)
print("la matrice des covariances :"'\n',pd.DataFrame(data=covMatrix))

la matrice des covariances :
         0      1      2       3
0  12.222 -0.889 -0.172 -15.556
1  -0.889  0.622  0.024   3.000
2  -0.172  0.024  0.006   0.225
3 -15.556  3.000  0.225  61.389


Question 8 : les coefficients de corrélations

In [10]:
#Coefficient de corrélation du couple :(Moyenne,Taille)
coefficient1 = np.corrcoef(data[:,0],data[:,2])

#Coefficient de corrélation du couple :(Age,Poids)
coefficient2 = np.corrcoef(data[:,1],data[:,3])

print("coefficient de corrélation entre (Moyenne,Taille):"'\n' ,np.round(coefficient1 , 3))
print("coefficient de corrélation entre (Age,Poids):" ,np.round(coefficient2 , 3))



coefficient de corrélation entre (Moyenne,Taille):
 [[ 1.    -0.629]
 [-0.629  1.   ]]
coefficient de corrélation entre (Age,Poids): [[1.    0.485]
 [0.485 1.   ]]


d'après les résultats obtenu on déduire que :
1- les deux variables (Moyenne,Taille) sont  linéairement liées dans le sens contraire car le coefficient et négative
2- les deux variables (Age,Poids) sont  linéairement liées (colinéaires) 

Question 9 : les valeurs et vecteurs propres du vecteur des covariances

In [11]:
valeurPropres, vecteurPropres =np.linalg.eig(covMatrix)

print("les valeurs propres:"'\n' ,np.round(valeurPropres , 3))
print("les vecteurs propres:"'\n' ,np.round(vecteurPropres , 3))



les valeurs propres:
 [6.6048e+01 7.7150e+00 4.7300e-01 3.0000e-03]
les vecteurs propres:
 [[-0.278  0.96  -0.016  0.014]
 [ 0.048 -0.003 -0.999 -0.024]
 [ 0.004 -0.013 -0.024  1.   ]
 [ 0.959  0.279  0.045  0.001]]


Distance entre les individus 

In [15]:
from scipy.spatial import distance

dis1 = distance.euclidean(data[3,:] , data[4,:])
dis2 = distance.euclidean(data[3,:] , data[5,:])
dis3 = distance.euclidean(data[4,:] , data[5,:])
print(round(dis1,2))
print(round(dis2,2))
print(round(dis3,2))

1.42
2.24
3.0


In [16]:
data[:,2] = data[:,2]*100

In [17]:
dis1 = distance.euclidean(data[3,:] , data[4,:])
dis2 = distance.euclidean(data[3,:] , data[5,:])
dis3 = distance.euclidean(data[4,:] , data[5,:])
print(round(dis1,2))
print(round(dis2,2))
print(round(dis3,2))

5.2
5.48
3.0


In [24]:
data = pd.DataFrame(data=data)
cormat = data.corr()
print(cormat)

          0         1         2         3
0  1.000000 -0.322329 -0.628737 -0.567892
1 -0.322329  1.000000  0.395515  0.485404
2 -0.628737  0.395515  1.000000  0.366516
3 -0.567892  0.485404  0.366516  1.000000
