In [1]:
import numpy as np

In [2]:
X = np.array (( [14,13,1.5,45], [16,13,1.6,50],[15,13,1.65,50],
            [9,15,1.75,60],[10,14,1.7,60],[7,14,1.7,60],
            [8,14,1.6,70],[13,13,1.6,65],[17,15,1.55,60],[11,14,1.7,65]))
X


array([[14.  , 13.  ,  1.5 , 45.  ],
       [16.  , 13.  ,  1.6 , 50.  ],
       [15.  , 13.  ,  1.65, 50.  ],
       [ 9.  , 15.  ,  1.75, 60.  ],
       [10.  , 14.  ,  1.7 , 60.  ],
       [ 7.  , 14.  ,  1.7 , 60.  ],
       [ 8.  , 14.  ,  1.6 , 70.  ],
       [13.  , 13.  ,  1.6 , 65.  ],
       [17.  , 15.  ,  1.55, 60.  ],
       [11.  , 14.  ,  1.7 , 65.  ]])

In [3]:
g = X.mean(0)
g

array([12.   , 13.8  ,  1.635, 58.5  ])

In [4]:
Y = X-g
Y

array([[  2.   ,  -0.8  ,  -0.135, -13.5  ],
       [  4.   ,  -0.8  ,  -0.035,  -8.5  ],
       [  3.   ,  -0.8  ,   0.015,  -8.5  ],
       [ -3.   ,   1.2  ,   0.115,   1.5  ],
       [ -2.   ,   0.2  ,   0.065,   1.5  ],
       [ -5.   ,   0.2  ,   0.065,   1.5  ],
       [ -4.   ,   0.2  ,  -0.035,  11.5  ],
       [  1.   ,  -0.8  ,  -0.035,   6.5  ],
       [  5.   ,   1.2  ,  -0.085,   1.5  ],
       [ -1.   ,   0.2  ,   0.065,   6.5  ]])

In [5]:
var = X.var(0)
var

array([1.100e+01, 5.600e-01, 5.525e-03, 5.525e+01])

In [6]:
ect = np.std(X,0)
ect

array([3.31662479, 0.74833148, 0.07433034, 7.43303437])

In [7]:
Z = Y/ect
Z

array([[ 0.60302269, -1.06904497, -1.81621654, -1.81621654],
       [ 1.20604538, -1.06904497, -0.47087096, -1.14354375],
       [ 0.90453403, -1.06904497,  0.20180184, -1.14354375],
       [-0.90453403,  1.60356745,  1.54714743,  0.20180184],
       [-0.60302269,  0.26726124,  0.87447463,  0.20180184],
       [-1.50755672,  0.26726124,  0.87447463,  0.20180184],
       [-1.20604538,  0.26726124, -0.47087096,  1.54714743],
       [ 0.30151134, -1.06904497, -0.47087096,  0.87447463],
       [ 1.50755672,  1.60356745, -1.14354375,  0.20180184],
       [-0.30151134,  0.26726124,  0.87447463,  0.87447463]])

In [8]:
cov = np.cov(X,rowvar=False,bias=True)
cov

array([[ 1.100e+01, -8.000e-01, -1.550e-01, -1.400e+01],
       [-8.000e-01,  5.600e-01,  2.200e-02,  2.700e+00],
       [-1.550e-01,  2.200e-02,  5.525e-03,  2.025e-01],
       [-1.400e+01,  2.700e+00,  2.025e-01,  5.525e+01]])

In [9]:
corr = np.corrcoef(X,rowvar=False)
corr

array([[ 1.        , -0.32232919, -0.62873728, -0.56789174],
       [-0.32232919,  1.        ,  0.39551461,  0.48540429],
       [-0.62873728,  0.39551461,  1.        ,  0.36651584],
       [-0.56789174,  0.48540429,  0.36651584,  1.        ]])

In [10]:
valeursProp , vecteursProp = np.linalg.eig(corr)
print(valeursProp)
print(vecteursProp)

[2.39089885 0.27438366 0.75031143 0.58440607]
[[ 0.53834812 -0.67153553 -0.43812579 -0.25935907]
 [-0.44530321  0.28548823 -0.70578764 -0.47123808]
 [-0.50383507 -0.5041931   0.46470353 -0.52534767]
 [-0.50797301 -0.46187209 -0.30652934  0.65930066]]


In [11]:
Propmat = np.column_stack((valeursProp , vecteursProp))
Propmat

array([[ 2.39089885,  0.53834812, -0.67153553, -0.43812579, -0.25935907],
       [ 0.27438366, -0.44530321,  0.28548823, -0.70578764, -0.47123808],
       [ 0.75031143, -0.50383507, -0.5041931 ,  0.46470353, -0.52534767],
       [ 0.58440607, -0.50797301, -0.46187209, -0.30652934,  0.65930066]])

In [101]:
Propmat.sort(0)
print(Propmat)

[[ 0.27438366 -0.50797301 -0.67153553 -0.70578764 -0.52534767]
 [ 0.58440607 -0.50383507 -0.5041931  -0.43812579 -0.47123808]
 [ 0.75031143 -0.44530321 -0.46187209 -0.30652934 -0.25935907]
 [ 2.39089885  0.53834812  0.28548823  0.46470353  0.65930066]]


In [102]:
Propmat = Propmat[Propmat[:, 0].argsort()]
Propmat

array([[ 0.27438366, -0.50797301, -0.67153553, -0.70578764, -0.52534767],
       [ 0.58440607, -0.50383507, -0.5041931 , -0.43812579, -0.47123808],
       [ 0.75031143, -0.44530321, -0.46187209, -0.30652934, -0.25935907],
       [ 2.39089885,  0.53834812,  0.28548823,  0.46470353,  0.65930066]])

In [103]:
valeursProp = sorted(valeursProp,reverse=True)

In [104]:
total_var = np.sum(valeursProp)

var_explained = valeursProp / total_var

cum_var_explained = np.cumsum(var_explained)

info_matrix = np.column_stack((valeursProp, var_explained, cum_var_explained))

info_matrix

array([[2.39089885, 0.59772471, 0.59772471],
       [0.75031143, 0.18757786, 0.78530257],
       [0.58440607, 0.14610152, 0.93140409],
       [0.27438366, 0.06859591, 1.        ]])

In [105]:
vecteursProp = Propmat[:,1:]
vecteursProp

array([[-0.50797301, -0.67153553, -0.70578764, -0.52534767],
       [-0.50383507, -0.5041931 , -0.43812579, -0.47123808],
       [-0.44530321, -0.46187209, -0.30652934, -0.25935907],
       [ 0.53834812,  0.28548823,  0.46470353,  0.65930066]])

In [106]:
axe1 =np.dot(Z,vecteursProp[0,:].T)
axe1

array([ 2.64759074,  1.03835612,  0.71675161, -1.81534729, -0.59636568,
       -0.13688681, -0.04729232,  0.43767374, -1.14156772, -1.10291239])

In [107]:
axe1var = axe1.var()
axe1var

1.498491632568609

In [108]:
axe2 =np.dot(Z,vecteursProp[1,:].T)
axe2

array([ 1.88678283,  0.67653922,  0.53373591, -1.12571358, -0.3091539 ,
        0.14658207, -0.0498774 ,  0.18130807, -1.16214829, -0.77805492])